// One-off utility: rewrites severityRank across all investigation JSON files
// according to the ordered slug list below. Run with: node scripts/renumber-ranks.js
const fs = require("fs");
const path = require("path");

const ORDER = [
  // Critical
  "coal-block-allocation-scam",
  "2g-spectrum-allocation-case",
  "mahadev-betting-app-scam",
  "sahara-sebi-case",
  "satyam-computers-scam",
  "bofors-scandal",
  "ilfs-crisis",
  "harshad-mehta-securities-scam",
  "dhfl-bank-fraud",
  "bhushan-power-steel-bank-fraud",
  "abg-shipyard-bank-fraud",
  "yes-bank-anil-ambani-fraud",
  "sterling-biotech-bank-fraud",
  "pacl-ponzi-scheme",
  "odisha-illegal-mining-scam",
  "amrapali-group-homebuyers-fraud",
  "jaypee-infratech-insolvency-homebuyers-case",
  "unitech-group-homebuyers-fraud",
  "speak-asia-online-ponzi-scheme",
  "gainbitcoin-cryptocurrency-ponzi-scheme",
  "neet-ug-2024-paper-leak-case",
  "antrix-devas-deal-case",
  "maharashtra-state-cooperative-bank-scam",
  "uttar-pradesh-food-grain-scam",
  "videocon-group-insolvency-collapse",
  "byjus-financial-collapse",
  "uti-us64-scheme-scandal",
  "kaleshwaram-lift-irrigation-project-scam",
  "maharashtra-irrigation-scam",
  "zee-entertainment-subhash-chandra-essel-loan-default-sebi",
  "digital-arrest-cyber-fraud-money-trail",
  "vodafone-idea-agr-dues-crisis",
  "balasore-train-collision-negligence-case",
  "1962-sino-indian-war-unpreparedness",
  "1971-war-bangladesh-liberation",
  "1975-emergency-shah-commission",
  "air-india-171-ahmedabad-crash",
  "bhopal-gas-tragedy-compensation-accountability",
  "kargil-1999-intelligence-failure",
  "operation-blue-star-1984-aftermath",
  "pahalgam-attack-operation-sindoor",
  "bihar-sir-electoral-rolls-case",
  "delhi-red-fort-blast-case",
  "green-revolution-self-sufficiency-costs",
  "india-us-tariff-trade-deal",
  "justice-yashwant-varma-cash-case",
  "maha-kumbh-2025-stampede",
  "manipur-presidents-rule-ethnic-violence",
  "pokhran-1974-peaceful-nuclear-explosion",
  "rcb-bengaluru-stampede",
  "uri-attack-surgical-strikes-2016",
  "1965-india-pakistan-war-tashkent",
  "1999-odisha-super-cyclone-preparedness-gap",
  "2001-gujarat-bhuj-earthquake-reconstruction",
  "2004-tsunami-early-warning-gap",
  "paytm-ipo-listing-crash",
  "pune-porsche-crash-juvenile-justice-case",
  "sebi-shell-companies-bogus-ltcg-crackdown",
  "2012-delhi-gangrape-nirbhaya-case",
  "26-11-mumbai-attacks-pradhan-committee",
  "rg-kar-medical-college-doctor-case",
  "2008-financial-crisis-sensex-crash",
  "2025-midcap-smallcap-market-correction",
  "air-india-boeing-aircraft-deal-case",
  "balakot-airstrike-disputed-claims",
  "indira-gandhi-assassination-thakkar-commission",
  "rajiv-gandhi-assassination-jain-commission",
  "jain-hawala-case",
  "telgi-stamp-paper-scam",
  "morbi-bridge-collapse",
  // Major
  "rose-valley-chit-fund-scam",
  "rhfl-bank-fraud",
  "dsk-group-real-estate-ponzi-case",
  "crb-capital-markets-scam",
  "chhattisgarh-liquor-scam",
  "charkhi-dadri-mid-air-collision",
  "chennai-2015-floods-urban-planning-failure",
  "kerala-2018-floods-dam-management-failure",
  "muzaffarpur-bihar-shelter-home-case",
  "uttarakhand-2013-kedarnath-floods-disaster-management-failure",
  "muzaffarpur-bihar-aes-child-deaths-2019",
  "covid-19-second-wave-oxygen-shortage-crisis-2021",
  "delhi-ncr-air-pollution-governance-failure",
  "gorakhpur-brd-medical-college-oxygen-deaths",
  "bank-of-baroda-hong-kong-forex-scam",
  "demonetisation-2016-outcomes",
  "gst-2017-rollout-implementation-failures",
  "reliance-capital-insolvency-case",
  "sahara-aamby-valley-asset-saga",
  "yes-bank-at1-bonds-writeoff-case",
  "delhi-excise-policy-case",
  "adani-group-hindenburg-doj-case",
  "commonwealth-games-2010-scam",
  "haryana-government-funds-fraud",
  "vijay-mallya-kingfisher-default",
  "reliance-communications-bob-fraud",
  "nsel-scam",
  "winsome-diamond-bank-fraud",
  "pnb-nirav-modi-fraud",
  "srei-infrastructure-finance-collapse",
  "karnataka-illegal-mining-scam",
  "pmc-bank-hdil-fraud",
  "agustawestland-chopper-scam",
  "yes-bank-rana-kapoor-fraud",
  "vyapam-scam",
  "fodder-scam",
  "west-bengal-teacher-recruitment-scam",
  "up-nrhm-scam",
  "neet-ug-2026-controversy",
  "national-herald-case",
  "cox-and-kings-fund-diversion-case",
  "franklin-templeton-mutual-fund-wind-up",
  "deccan-chronicle-bank-loan-fraud-case",
  "uksssc-recruitment-paper-leak-scam",
  "tspsc-paper-leak-case",
  "hssc-constable-paper-leak-scam",
  "reet-2021-paper-leak-scandal",
  "ugc-net-2024-cancellation-case",
  "haryana-jbt-teacher-recruitment-scam",
  "bihar-shikshak-bahali-fake-certificate-scam",
  "punjab-foodgrain-procurement-tender-scam",
  "amtek-auto-insolvency-case",
  "bharatpe-ashneer-grover-dispute",
  "bihar-srijan-scam",
  "bmc-covid-ppe-mask-procurement-scam",
  "chhattisgarh-coal-levy-scam",
  "essar-steel-insolvency-case",
  "global-trust-bank-collapse",
  "hdw-submarine-scam",
  "iifl-finance-gold-loan-ban",
  "ima-ponzi-scheme",
  "jpsc-recruitment-scam",
  "madhya-pradesh-e-tendering-scam",
  "pincon-group-ponzi-scheme",
  "rafale-deal-controversy",
  "religare-finvest-fund-diversion-case",
  "srs-group-ponzi-scheme",
  "tatra-truck-scam",
  "karnataka-40-percent-commission-allegations",
  "karnataka-psi-recruitment-scam",
  "nsdl-ipo-demat-account-scam",
  "go-first-airlines-insolvency",
  "home-trade-dot-com-scam",
  "kerala-gold-smuggling-case",
  "andhra-pradesh-skill-development-corporation-scam",
  "bank-of-rajasthan-icici-merger-scam",
  "lic-housing-finance-loan-for-bribe-scam",
  "odisha-seashore-chit-fund-scam",
  "ayushman-bharat-pmjay-fraud",
  "concast-steel-power-bank-fraud",
  "jharkhand-bengal-gst-fake-invoice-scam",
  "karuvannur-cooperative-bank-scam",
  "paytm-payments-bank-rbi-restrictions",
  "tata-sons-cyrus-mistry-removal-case",
  "tamil-nadu-beach-sand-mining-scam",
  "pmkvy-skill-development-fake-beneficiaries",
  "tasmac-liquor-corporation-scam",
  "andhra-pradesh-liquor-scam",
  "karnataka-valmiki-corporation-scam",
  "ketan-desai-mci-bribery-scandal",
  "nk-proteins-nsel-default",
  "rajasthan-si-recruitment-2021-paper-leak",
  "satyendar-jain-money-laundering-case",
  "up-nrhm-cmo-murders-conviction",
  "idbi-kingfisher-officials-cbi-case",
  "nsel-ark-imports-default",
  "punjab-sind-bank-surya-pharmaceuticals-fraud",
  "adani-coal-over-invoicing-dri-case",
  "cosmos-bank-cyber-heist",
  "crown-credit-cooperative-society-punjab-scam",
  "maytas-properties-land-fraud-case",
  "mumbai-metro-aarey-car-shed-cost-overrun",
  "gst-2-0-reform-2025",
  "1975-sikkim-merger-referendum",
  "1989-karnataka-bommai-presidents-rule-case",
  "1993-latur-earthquake-reconstruction",
  "2010-mangalore-air-india-express-crash",
  "cian-agro-industries-ethanol-stock-surge",
  "mizo-insurgency-1986-peace-accord",
  "sebi-superior-finlease-pump-and-dump",
  "uphaar-cinema-fire-1997",
  "sukh-ram-telecom-corruption-case",
  "air-india-sita-data-breach",
  "national-highway-road-quality-failures-case",
  "vivekananda-flyover-collapse-kolkata",
  "chinese-loan-app-payment-gateway-fraud-case",
  "madhu-koda-coal-scam",
  "jayalalithaa-sasikala-disproportionate-assets-case",
  "ranbaxy-usfda-adulterated-drugs-fraud",
  "maiden-pharmaceuticals-gambia-cough-syrup-deaths",
  "maruti-suzuki-manesar-violence-case",
  "chhattisgarh-nan-pds-scam",
  "rajasthan-jal-jeevan-mission-scam",
  "bichhri-village-pollution-case",
  "namami-gange-mission-failure",
  "csmt-himalaya-bridge-collapse-mumbai",
  "sunil-kedar-nagpur-cooperative-bank-scam",
  "sukesh-chandrashekhar-extortion-case",
  "sterlite-copper-thoothukudi-closure",
  "bombay-hc-pothole-liability-ruling",
  "new-india-cooperative-bank-fraud",
  // Moderate
  "saradha-chit-fund-scam",
  "ketan-parekh-securities-scam",
  "karvy-stock-broking-scam",
  "prayag-group-chit-fund-scam",
  "fortis-religare-singh-brothers-fraud",
  "rotomac-loan-fraud",
  "icici-videocon-loan-case",
  "karti-chidambaram-inx-media-case",
  "land-for-jobs-scam",
  "adarsh-housing-society-scam",
  "aircel-maxis-deal",
  "reliance-communications-ericsson-contempt",
  "ram-mandir-trust-financial-controversies",
  "reliance-kg-d6-gas-pricing-dispute",
  "hemant-soren-land-case",
  "ipl-spot-fixing-scandal",
  "west-bengal-cattle-smuggling-case",
  "narada-sting-case",
  "bpsc-70th-paper-leak-controversy",
  "assam-sarba-siksha-abhiyan-scam",
  "dda-land-allotment-scam",
  "citibank-gurgaon-relationship-manager-fraud",
  "delhi-jal-board-tanker-scam",
  "emu-farming-scam",
  "kargil-coffins-scam",
  "madhya-pradesh-ppe-kit-procurement-scam",
  "pm-kisan-scheme-irregularities",
  "reebok-india-accounting-fraud",
  "sukhna-land-scam",
  "punjab-illegal-sand-mining-scam",
  "madhya-pradesh-scholarship-scam",
  "andhra-pradesh-fibernet-scam",
  "snc-lavalin-kerala-hydroelectric-case",
  "aakash-educational-services-promoter-dispute",
  "infosys-whistleblower-complaint-2019",
  "reliance-jio-predatory-pricing-case",
  "whatsapp-meta-cci-antitrust-case",
  "sebi-hanif-shekh-pump-and-dump-scam",
  "army-colonel-defence-tender-bribery-case",
  "bihar-illegal-sand-mining-scam",
  "pm-awas-yojana-fake-beneficiaries-scam",
  "delhi-cng-fitness-certificate-scam",
  "jharkhand-hemant-soren-mining-lease-case",
  "pnb-kanishk-gold-loan-fraud",
  "punjab-driving-licence-scam",
  "rajasthan-bharatpur-illegal-mining-scam",
  "sahara-q-shop-mlm-scheme",
  "sebi-irda-ulip-turf-war",
  "uttar-pradesh-hamirpur-illegal-mining-case",
  "barak-missile-deal-cbi-case",
  "iipm-fake-accreditation-case",
  "max-life-axis-bank-irdai-bancassurance-case",
  "jio-airtel-vodafone-interconnection-cartel-case",
  "reliance-disney-jiocinema-merger-cci-case",
  "ghazipur-landfill-collapse",
  "nestle-maggi-lead-controversy",
  "kodaikanal-mercury-poisoning-case",
  "jamtara-vishing-gang-conviction",
  "colonel-vikas-pandey-army-fund-fraud",
  // Minor
  "mgnrega-fund-misappropriation",
  "jeep-scandal-1948",
  "ethanol-tender-bid-rigging-case",
  "rajasthan-patwari-recruitment-exam-scam",
  "hdil-union-bank-guruashish-fraud",
  "neesa-technologies-ncd-fraud",
  "pnb-gupta-power-infrastructure-fraud",
];

const dir = path.join(__dirname, "..", "content", "investigations");
const files = fs.readdirSync(dir).filter((f) => f.endsWith(".json"));

const bySlug = new Map();
for (const file of files) {
  const full = path.join(dir, file);
  const data = JSON.parse(fs.readFileSync(full, "utf-8"));
  bySlug.set(data.slug, { file: full, data });
}

const missingFromOrder = [...bySlug.keys()].filter((s) => !ORDER.includes(s));
const missingFile = ORDER.filter((s) => !bySlug.has(s));
if (missingFromOrder.length) {
  console.error("Slugs present as files but missing from ORDER:", missingFromOrder);
  process.exit(1);
}
if (missingFile.length) {
  console.error("Slugs in ORDER but missing a file:", missingFile);
  process.exit(1);
}

ORDER.forEach((slug, i) => {
  const rank = i + 1;
  const entry = bySlug.get(slug);
  entry.data.severityRank = rank;
  fs.writeFileSync(entry.file, JSON.stringify(entry.data, null, 2) + "\n", "utf-8");
});

console.log(`Renumbered ${ORDER.length} files, ranks 1..${ORDER.length}.`);
